### ISSUE TITLE
MACH bug

### ISSUE THREAD

**Issue by tsourolampis** [hayasick/CTFT#1]
Hi -- I took a look at your code. There seems to be a bug that results in a bad low rank approximation for MACH.  Line 48 should be something like X_sp = st.sptensor(multinds,  1/p*X[multinds], shape=X.shape), i.e., each entry that ''survives'' the sampling gets reweighted by 1/p.

**Comment by hayasick** [comment]
Hi Charalampos, 
Thanks! I fixed the bug. Now I'm re-running the experiments to see how the bug degraded the performance.

**Comment by hayasick** [comment]
I've finished the experiments and confirmed that the performance of MACH is certainly increased. I revised the NIPS paper and it will be appeared in next few months.

**Comment by tsourolampis** [comment]
Sounds great, thanks!

Regards,
